### ISSUE TITLE
UndefinedError: 'trigger' is undefined

### ISSUE THREAD

**Issue by TFenby** [gazoscalvertos/Hass-Custom-Alarm#12]
Automations based on a 'to: armed_away' don't have access to trigger in their data_template.

Works:
```
- id: alarm_disarmed
  alias: '[Alarm] Disarmed'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'disarmed'
  action:
    - service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: XXX
    - service: script.sms_message
      data_template:
        message: '{{ trigger.to_state.name }}: {{ trigger.to_state.state }}'
```

Doesn't work:
```
- id: alarm_armed_away
  alias: '[Alarm] Away Mode Armed'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'armed_away'
  action:
    - service: script.sms_message
      data_template:
        message: '{{ trigger.to_state.name }}: {{ trigger.to_state.state }}'
```
