### ISSUE TITLE
override sensors remain ignored after arming, and immediate sensors don't trigger during warning

### ISSUE THREAD

**Issue by jcooper-korg** [gazoscalvertos/Hass-Custom-Alarm#38]
related to #15 

 I noticed an issue with “override sensors”. I have set up my armed_away mode as follows:

```
 armed_away: 
  #[OPTIONAL] State specific overrides default time above
  trigger_time: 600  
  ##[OPTIONAL however either an immediate or delayed group must exist] Sensors in this group tigger the alarm immediately 
  immediate:
    - binary_sensor.door_side_garage
    - binary_sensor.window_office
    - binary_sensor.window_living_room
    - binary_sensor.window_dining_room
    - binary_sensor.window_master_bedroom
  ##[OPTIONAL] Sensors in this group start the clock (pending_time) when tripped before the alarm is triggered 
  delayed:
    - binary_sensor.door_front
    - binary_sensor.door_garage
  #[OPTIONAL] Use this group to automatically override the warning message on open sensors when arming. (I use this as I have a motion sensor at the front door)
  override:
    - binary_sensor.motion_hall
    - binary_sensor.motion_living_room
```
I specified “override” for the motion sensors for the same reason as specified in the comments- I need to be able to walk around the doors while arming and leaving. That works.

However, once the alarm is armed_away, the motion sensors remain on the inactive list, and do not trigger the siren if there is motion. Really, they should only be ignored while in the pending arming stage, and they should trigger the siren immediately if there is motion after arming. 

Furthermore,  it appears that immediate zones do not trigger during the re-entry warning state. That doesn’t seem right.
If the alarm is armed away, and I open the front door, it starts the warning count-down ok- but if I then open or break a window while still counting-down, it really should trigger the alarm. And in this state, the motion detectors should be overridden to allow walking down the hall to turn off the alarm.
Based on the comments, it seems that’s what the override option in alarm.yaml is intended for, but it’s not working that way.
