### ISSUE TITLE
[FEATURE REQ] Silent Mode

### ISSUE THREAD

**Issue by pharpe** [gazoscalvertos/Hass-Custom-Alarm#45]
Thanks for all your work on this.  I'd like to have an option to for a silent mode.  Meaning if triggered I want to get my push bullet notifications but not turn on the siren.  I know I can comment out the action `  - entity_id: switch.siren
    service: switch.turn_on `
but I would like the option in the Alarm panel to control if the siren will go off if alarm is triggered.

**Comment by gazoscalvertos** [comment]
I'll add it to the list.

You could also implement this in the meantime using automations:

1st Automation for notification
```
- id: alarm_triggered
  alias: '[Alarm] Trigger Notification'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'triggered'
  action:
  - service: notify.pushbullet
    data:
      message: 'ALARM TRIGGERED!!! {{ states[states.alarm_control_panel.house.attributes.changed_by.split(".")[0]][ states.alarm_control_panel.house.attributes.changed_by.split(".")[1]].name }}'
      target: email/example@gmail.com
```
2nd Automation for siren using an input_boolean:
```
- id: alarm_triggered
  alias: '[Alarm] Triggered'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'triggered'
condition:
  - condition: state
    entity_id: 'input_boolean.silence_siren'
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.siren_switch
```
add an input_boolean to your configuration.yaml
```
input_boolean:
  silence_siren:
    name: Silence Siren
```

You can then use this new input boolean as a switch in your home assistant front end to switch siren trigger on and off
